{{- if and .Values.messaging.enabled .Values.messaging.kafka.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.messaging.kafka.name }}-storage-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-database.messaging.labels" . | nindent 4 }}
    app: {{ .Values.messaging.kafka.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.messaging.kafka.storage.size }}
  storageClassName: {{ .Values.global.storageClass }}
{{- end }}