{{- if .Values.kafkaUI.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kafkaUI.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-tools.kafkaui.labels" . | nindent 4 }}
    app: {{ .Values.kafkaUI.name }}
  annotations:
    {{- include "nexus-tools.annotations" . | nindent 4 }}
data:
  config.yml: |
    kafka:
      clusters:
        - name: nexus-commerce-kafka
          bootstrapServers: {{ .Values.kafkaUI.config.kafka.bootstrapServers }}
          zookeeper: {{ .Values.kafkaUI.config.kafka.zookeeper }}
          properties: {}
          readOnly: false
          metrics:
            port: 9997
            type: JMX
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
    spring:
      security:
        oauth2:
          client:
            registration: {}
{{- end }}