{{- if .Values.kafkaUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaUI.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-tools.kafkaui.labels" . | nindent 4 }}
    app: {{ .Values.kafkaUI.name }}
  annotations:
    {{- include "nexus-tools.annotations" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.kafkaUI.name }}
  ports:
    - name: http
      port: {{ .Values.kafkaUI.service.port }}
      targetPort: {{ .Values.kafkaUI.service.port }}
      protocol: TCP
  type: {{ .Values.kafkaUI.service.type }}
{{- end }}