{{- if .Values.global.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-observability.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace }}
{{- end }}