{{- if and .Values.mongodb.enabled .Values.mongodb.cart.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongodb.cart.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-database.mongodb.labels" . | nindent 4 }}
    app: {{ .Values.mongodb.cart.name }}
    service: cart-service
data:
  database-name: {{ .Values.mongodb.cart.database.name | quote }}
  mongodb-url: "mongodb://{{ .Values.mongodb.cart.name }}-headless.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.mongodb.cart.service.port }}/{{ .Values.mongodb.cart.database.name }}"
  mongod.conf: |
    storage:
      dbPath: /data/db
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          cacheSizeGB: 0.5
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
      logRotate: reopen
    net:
      port: {{ .Values.mongodb.cart.service.port }}
      bindIp: 0.0.0.0
      maxIncomingConnections: 100
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
    replication:
      replSetName: "cart-replica-set"
    security:
      authorization: enabled
{{- end }}