{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-observability.prometheus.labels" . | nindent 4 }}
    app: {{ .Values.prometheus.name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.prometheus.name }}
  labels:
    {{- include "nexus-observability.prometheus.labels" . | nindent 4 }}
    app: {{ .Values.prometheus.name }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prometheus.name }}
  labels:
    {{- include "nexus-observability.prometheus.labels" . | nindent 4 }}
    app: {{ .Values.prometheus.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prometheus.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.name }}
    namespace: {{ .Values.global.namespace }}
{{- end }}