global:
  namespace: tools
  environment: production
  storageClass: standard
  nodeSelector:
    node-role: infrastructure

  # Global resource defaults
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Kafka UI Configuration
kafkaUI:
  enabled: true
  name: kafka-ui
  image:
    repository: provectuslabs/kafka-ui
    tag: "latest"
    pullPolicy: IfNotPresent

  replicas: 1

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  service:
    type: ClusterIP
    port: 8080

  config:
    kafka:
      bootstrapServers: "kafka-service.data.svc.cluster.local:9092"
      zookeeper: "zookeeper-service.data.svc.cluster.local:2181"

