global:
  namespace: tools
  environment: development
  storageClass: standard
  nodeSelector:
    node-role: infrastructure

# Kafka UI Configuration for Development
kafkaUI:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Prometheus Configuration for Development
prometheus:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"

  storage:
    size: 2Gi  # Smaller storage for dev

  config:
    retention: "7d"  # Shorter retention for dev

# Grafana Configuration for Development
grafana:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  storage:
    size: 1Gi  # Smaller storage for dev

  config:
    adminPassword: "dev123"  # Simple password for dev

# Swagger UI Configuration for Development
swaggerUI:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "64Mi"
      cpu: "50m"

# Adminer Configuration for Development
adminer:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "16Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "50m"

# pgAdmin Configuration for Development
pgAdmin:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  storage:
    size: 500Mi  # Smaller storage for dev

  config:
    defaultPassword: "dev123"

# Redis Commander Configuration for Development
redisCommander:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "32Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "50m"

# Jaeger Configuration for Development (if needed)
jaeger:
  enabled: false  # Keep disabled for dev

# Kiali Configuration for Development
kiali:
  enabled: false  # Disable for dev unless testing Istio

# ElasticSearch for Development
elasticsearch:
  enabled: false  # Disable for dev to save resources

# Kibana for Development
kibana:
  enabled: false  # Disable for dev to save resources

# Ingress Configuration for Development
ingress:
  enabled: true
  hosts:
    - host: tools.nexus-commerce.local
      paths:
        - path: /kafka-ui
          pathType: Prefix
          service: kafka-ui
          port: 8080
        - path: /grafana
          pathType: Prefix
          service: grafana
          port: 3000
        - path: /prometheus
          pathType: Prefix
          service: prometheus
          port: 9090
        - path: /swagger
          pathType: Prefix
          service: swagger-ui
          port: 8080
        - path: /adminer
          pathType: Prefix
          service: adminer
          port: 8080
        - path: /pgadmin
          pathType: Prefix
          service: pgadmin
          port: 80
        - path: /redis
          pathType: Prefix
          service: redis-commander
          port: 8081

# Security for Development
security:
  enabled: false  # Relaxed security for dev
  networkPolicies:
    enabled: false

# Monitoring for Development
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false  # Disable service monitor for dev
  healthChecks:
    enabled: true