global:
  namespace: tools
  environment: production
  storageClass: fast-ssd
  nodeSelector:
    node-role: infrastructure

# Kafka UI Configuration for Production
kafkaUI:
  enabled: true
  replicas: 2  # High availability

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Prometheus Configuration for Production
prometheus:
  enabled: true
  replicas: 2  # High availability

  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  storage:
    size: 50Gi  # Large storage for production

  config:
    retention: "90d"  # Longer retention for production
    scrapeInterval: "15s"
    evaluationInterval: "15s"

# Grafana Configuration for Production
grafana:
  enabled: true
  replicas: 2  # High availability

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  storage:
    size: 10Gi

  config:
    adminPassword: "ChangeMeInProduction!"  # Strong password needed
    datasources:
      prometheus:
        enabled: true
        url: "http://prometheus.tools.svc.cluster.local:9090"

# Swagger UI Configuration for Production
swaggerUI:
  enabled: true
  replicas: 2

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Adminer Configuration for Production
adminer:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# pgAdmin Configuration for Production
pgAdmin:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  storage:
    size: 5Gi

  config:
    defaultPassword: "ChangeMeInProduction!"

# Redis Commander Configuration for Production
redisCommander:
  enabled: true
  replicas: 1

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Jaeger Configuration for Production (alternative to Zipkin)
jaeger:
  enabled: false  # Keep disabled if using Zipkin

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  storage:
    size: 10Gi

# Kiali Configuration for Production (if using Istio)
kiali:
  enabled: false  # Enable if using Istio service mesh

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"

# ElasticSearch for Production (centralized logging)
elasticsearch:
  enabled: true  # Enable for production logging

  replicas: 3  # High availability

  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  storage:
    size: 100Gi  # Large storage for logs

# Kibana for Production
kibana:
  enabled: true  # Enable for production log analysis

  replicas: 2

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

# Ingress Configuration for Production
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - secretName: tools-tls-secret
      hosts:
        - tools.nexus-commerce.com
  hosts:
    - host: tools.nexus-commerce.com
      paths:
        - path: /kafka-ui
          pathType: Prefix
          service: kafka-ui
          port: 8080
        - path: /grafana
          pathType: Prefix
          service: grafana
          port: 3000
        - path: /prometheus
          pathType: Prefix
          service: prometheus
          port: 9090
        - path: /swagger
          pathType: Prefix
          service: swagger-ui
          port: 8080
        - path: /adminer
          pathType: Prefix
          service: adminer
          port: 8080
        - path: /pgadmin
          pathType: Prefix
          service: pgadmin
          port: 80
        - path: /redis
          pathType: Prefix
          service: redis-commander
          port: 8081
        - path: /elasticsearch
          pathType: Prefix
          service: elasticsearch
          port: 9200
        - path: /kibana
          pathType: Prefix
          service: kibana
          port: 5601

# Security for Production
security:
  enabled: true
  networkPolicies:
    enabled: true
  rbac:
    enabled: true

# Monitoring for Production
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
  healthChecks:
    enabled: true

# Backup for Production
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 30  # Keep for 30 days
  destinations:
    - s3
    - gcs

# Alerting for Production
alerting:
  enabled: true
  rules:
    - name: HighMemoryUsage
      condition: "memory_usage > 80%"
      severity: warning
    - name: HighCPUUsage
      condition: "cpu_usage > 90%"
      severity: critical
    - name: ServiceDown
      condition: "up == 0"
      severity: critical