{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-database.redis.labels" . | nindent 4 }}
    app: {{ .Values.redis.name }}
spec:
  selector:
    app: {{ .Values.redis.name }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
  type: {{ .Values.redis.service.type }}
{{- end }}