{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.name }}-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-database.redis.labels" . | nindent 4 }}
    app: {{ .Values.redis.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
  storageClassName: {{ .Values.global.storageClass }}
{{- end }}
