{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-observability.elasticsearch.labels" . | nindent 4 }}
    app: {{ .Values.elasticsearch.name }}
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  template:
    metadata:
      labels:
        {{- include "nexus-observability.elasticsearch.labels" . | nindent 8 }}
        app: {{ .Values.elasticsearch.name }}
    spec:
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.elasticsearch.service.ports.http }}
            - name: transport
              containerPort: {{ .Values.elasticsearch.service.ports.transport }}
          env:
            - name: discovery.type
              value: {{ .Values.elasticsearch.config.discoveryType | quote }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.config.javaOpts | quote }}
            - name: xpack.security.enabled
              value: {{ .Values.elasticsearch.config.xpackSecurityEnabled | quote }}
            - name: xpack.security.enrollment.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: cluster.name
              value: {{ .Values.elasticsearch.config.clusterName | quote }}
            - name: node.name
              value: {{ .Values.elasticsearch.config.nodeName | quote }}
            - name: network.host
              value: "0.0.0.0"
            - name: http.port
              value: {{ .Values.elasticsearch.service.ports.http | quote }}
            - name: transport.port
              value: {{ .Values.elasticsearch.service.ports.transport | quote }}
            - name: indices.fielddata.cache.size
              value: "20%"
            - name: indices.query.bool.max_clause_count
              value: "10000"
            - name: action.auto_create_index
              value: "true"
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.elasticsearch.service.ports.http }}
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.elasticsearch.service.ports.http }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.elasticsearch.service.ports.http }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: elasticsearch-data
          {{- if .Values.elasticsearch.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.elasticsearch.name }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: elasticsearch-config
          configMap:
            name: {{ .Values.elasticsearch.name }}-config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
{{- end }}