{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-observability.elasticsearch.labels" . | nindent 4 }}
    app: {{ .Values.elasticsearch.name }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.ports.http }}
      targetPort: {{ .Values.elasticsearch.service.ports.http }}
      protocol: TCP
    - name: transport
      port: {{ .Values.elasticsearch.service.ports.transport }}
      targetPort: {{ .Values.elasticsearch.service.ports.transport }}
      protocol: TCP
  type: {{ .Values.elasticsearch.service.type }}
{{- end }}