{{- if .Values.kiali.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kiali.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-observability.kiali.labels" . | nindent 4 }}
    app: {{ .Values.kiali.name }}
spec:
  replicas: {{ .Values.kiali.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kiali.name }}
  template:
    metadata:
      labels:
        {{- include "nexus-observability.kiali.labels" . | nindent 8 }}
        app: {{ .Values.kiali.name }}
    spec:
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.kiali.name }}-service-account
      containers:
        - name: kiali
          image: "{{ .Values.kiali.image.repository }}:{{ .Values.kiali.image.tag }}"
          imagePullPolicy: {{ .Values.kiali.image.pullPolicy }}
          command:
            - "/opt/kiali/kiali"
            - "-config"
            - "/kiali-configuration/config.yaml"
          ports:
            - name: api-port
              containerPort: {{ .Values.kiali.service.ports.http }}
              protocol: TCP
            - name: http-metrics
              containerPort: {{ .Values.kiali.service.ports.metrics }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          env:
            - name: ACTIVE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "text"
            - name: LOG_TIME_FIELD_FORMAT
              value: "2006-01-02T15:04:05Z07:00"
            - name: LOG_SAMPLER_RATE
              value: "1"
          volumeMounts:
            - name: kiali-configuration
              mountPath: "/kiali-configuration"
            - name: kiali-cert
              mountPath: "/kiali-cert"
            - name: kiali-secret
              mountPath: "/kiali-secret"
          resources:
            {{- toYaml .Values.kiali.resources | nindent 12 }}
      volumes:
        - name: kiali-configuration
          configMap:
            name: {{ .Values.kiali.name }}-config
        - name: kiali-cert
          secret:
            secretName: istio.{{ .Values.kiali.name }}-service-account
            optional: true
        - name: kiali-secret
          secret:
            secretName: {{ .Values.kiali.name }}
            optional: true
{{- end }}