{{- if and .Values.postgresql.enabled .Values.postgresql.payment.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.payment.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-database.postgresql.labels" . | nindent 4 }}
    app: {{ .Values.postgresql.payment.name }}
    service: payment-service
spec:
  serviceName: {{ .Values.postgresql.payment.name }}-service
  replicas: {{ .Values.postgresql.payment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgresql.payment.name }}
  template:
    metadata:
      labels:
        {{- include "nexus-database.postgresql.labels" . | nindent 8 }}
        app: {{ .Values.postgresql.payment.name }}
        service: payment-service
    spec:
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.payment.image.repository }}:{{ .Values.postgresql.payment.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.payment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgresql.payment.service.port }}
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.payment.database.name }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.payment.name }}-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.payment.name }}-secret
                  key: password
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-local=trust --auth-host=scram-sha-256"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql
              readOnly: true
          resources:
            {{- toYaml .Values.postgresql.payment.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
                - -d
                - $(POSTGRES_DB)
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
                - -d
                - $(POSTGRES_DB)
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
                - -d
                - $(POSTGRES_DB)
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
      volumes:
        - name: postgres-config
          configMap:
            name: {{ .Values.postgresql.payment.name }}-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          {{- include "nexus-database.postgresql.labels" . | nindent 10 }}
          app: {{ .Values.postgresql.payment.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresql.payment.storage.size }}
        storageClassName: {{ .Values.global.storageClass }}
{{- end }}
