{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ingress.name }}-serviceaccount
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-infrastructure.ingress.labels" . | nindent 4 }}
    app: {{ .Values.ingress.name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.ingress.name }}-clusterrole
  labels:
    {{- include "nexus-infrastructure.ingress.labels" . | nindent 4 }}
    app: {{ .Values.ingress.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.ingress.name }}-clusterrolebinding
  labels:
    {{- include "nexus-infrastructure.ingress.labels" . | nindent 4 }}
    app: {{ .Values.ingress.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.ingress.name }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.ingress.name }}-serviceaccount
    namespace: {{ .Values.global.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.ingress.name }}-role
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-infrastructure.ingress.labels" . | nindent 4 }}
    app: {{ .Values.ingress.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - ingress-controller-leader
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.ingress.name }}-rolebinding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-infrastructure.ingress.labels" . | nindent 4 }}
    app: {{ .Values.ingress.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.ingress.name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.ingress.name }}-serviceaccount
    namespace: {{ .Values.global.namespace }}
{{- end }}
