{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ingress.name }}-configuration
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-infrastructure.ingress.labels" . | nindent 4 }}
    app: {{ .Values.ingress.name }}
data:
  enable-cors: {{ .Values.ingress.config.enableCors | quote }}
  cors-allow-methods: {{ .Values.ingress.config.corsAllowMethods | quote }}
  cors-allow-headers: {{ .Values.ingress.config.corsAllowHeaders | quote }}
  client-max-body-size: {{ .Values.ingress.config.clientMaxBodySize | quote }}
  proxy-connect-timeout: {{ .Values.ingress.config.proxyConnectTimeout | quote }}
  proxy-read-timeout: {{ .Values.ingress.config.proxyReadTimeout | quote }}
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
  worker-processes: "auto"
  worker-connections: "1024"
  max-worker-open-files: "2048"
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
  rate-limit-rpm: "100"
{{- end }}