{{- if .Values.logstash.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logstash.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-observability.logstash.labels" . | nindent 4 }}
    app: {{ .Values.logstash.name }}
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    http.port: {{ .Values.logstash.service.ports.monitoring }}
    path.config: /usr/share/logstash/pipeline
    path.data: /usr/share/logstash/data
    pipeline.workers: 2
    pipeline.batch.size: 125
    pipeline.batch.delay: 50
    queue.type: memory
    queue.page_capacity: 64mb
    queue.max_events: 0
    queue.max_bytes: 1024mb
    dead_letter_queue.enable: false
    log.level: info
    xpack.monitoring.enabled: false
    config.reload.automatic: true
    config.reload.interval: 3s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logstash.name }}-pipeline
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexus-observability.logstash.labels" . | nindent 4 }}
    app: {{ .Values.logstash.name }}
data:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => {{ .Values.logstash.config.kafkaBootstrapServers | quote }}
        topics => ["app-logs"]
        codec => "json"
        group_id => "logstash-microservices-group"
        client_id => "logstash-consumer"
        auto_offset_reset => "earliest"
        consumer_threads => 1
        decorate_events => true
        security_protocol => "PLAINTEXT"
      }
    }

    filter {
      # Only process if JSON parsing succeeded
      if "_jsonparsefailure" not in [tags] {

        # Add processing timestamp
        mutate {
          add_field => { "logstash_processed_at" => "%{+yyyy-MM-dd HH:mm:ss}" }
        }

        # Fix timestamp parsing - handle multiple formats
        if [@timestamp] {
          date {
            match => [
              "@timestamp",
              "ISO8601",
              "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
              "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
              "yyyy-MM-dd'T'HH:mm:ss'Z'"
            ]
            target => "@timestamp"
          }
        }

        # Ensure required fields exist
        if ![level] {
          mutate { add_field => { "level" => "INFO" } }
        }
        if ![service_name] {
          mutate { add_field => { "service_name" => "unknown" } }
        }
        if ![logger_name] {
          mutate { add_field => { "logger_name" => "unknown" } }
        }

        # Parse Kubernetes metadata if present
        if [kubernetes] {
          mutate {
            add_field => { "k8s_namespace" => "%{[kubernetes][namespace]}" }
            add_field => { "k8s_pod" => "%{[kubernetes][pod]}" }
            add_field => { "k8s_container" => "%{[kubernetes][container]}" }
          }
        }

        # Add environment tag
        mutate {
          add_field => { "environment" => "{{ .Values.global.environment }}" }
          add_field => { "cluster" => "nexus-commerce" }
        }
      }
    }

    output {
      elasticsearch {
        hosts => [{{ .Values.logstash.config.elasticsearchHosts | quote }}]
        index => "microservices-logs-%{+yyyy.MM.dd}"
        document_type => "_doc"
        template_overwrite => true
        template_name => "microservices-logs"
        template => {
          "index_patterns" => ["microservices-logs-*"]
          "settings" => {
            "number_of_shards" => 1
            "number_of_replicas" => 0
            "index.refresh_interval" => "5s"
          }
          "mappings" => {
            "properties" => {
              "@timestamp" => { "type" => "date" }
              "level" => { "type" => "keyword" }
              "service_name" => { "type" => "keyword" }
              "logger_name" => { "type" => "keyword" }
              "message" => { "type" => "text" }
              "thread_name" => { "type" => "keyword" }
              "environment" => { "type" => "keyword" }
              "cluster" => { "type" => "keyword" }
            }
          }
        }
      }

      # Debug output (remove in production)
      stdout {
        codec => rubydebug {
          metadata => false
        }
      }
    }
{{- end }}